#!/bin/bash
dt=`date +"%Y-%m-%d-%T"` #videofil format

cd ~/pi-pic/
raspivid -o origVid.h264 -fps 15 -t 10000 #optag 10 sek
MP4Box -add origVid.h264 -fps 15 temp.mp4 #encode

ffmpeg -ss 5 -i temp.mp4 -c copy -t 1 trimVid.mp4 #trim fra 5 sek og 1 sek frem

if [ ! -d "$1" ]; then #opret directory
	mkdir $1
fi
cp trimVid.mp4 $1/$dt.mp4 #kopier video med 'dt' navnformat til mappen


#mv temp.mp4 trimVid.mp4
file="finalVideo.mp4" #TODO: ændr til $1

if [ -f "$file" ] #hvis filen eksisterer
then # konkatener filerne
	ffmpeg -f concat -i listOfFiles.txt -c copy joinedVideo.mp4
	mv joinedVideo.mp4 finalVideo.mp4
	rm trimVid.mp4
else #ellers omdøbes filen blot
	mv trimVid.mp4 finalVideo.mp4
fi

# fjern temp filer
rm temp.mp4 
rm origVid.h264
