#!/bin/bash
dt=`date +"%Y-%m-%d-%T"`

cd ~/Documents/ChristiansKode/autoBilleder
raspivid -o origVid.h264 -fps 15 -t 10000
MP4Box -add origVid.h264 -fps 15 temp.mp4

ffmpeg -ss 5 -i temp.mp4 -c copy -t 1 trimVid.mp4

if [ ! -d "$1" ]; then
	mkdir $1
fi
cp trimVid.mp4 $1/$dt.mp4


#mv temp.mp4 trimVid.mp4
file="finalVideo.mp4"

if [ -f "$file" ]
then
	ffmpeg -f concat -i listOfFiles.txt -c copy joinedVideo.mp4
	mv joinedVideo.mp4 finalVideo.mp4
	rm trimVid.mp4
else
	mv trimVid.mp4 finalVideo.mp4
fi
rm temp.mp4
rm origVid.h264
